[tool.black]
line-length = 99
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | venv
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap=0
use_parentheses = true
line_length = 88
float_to_top = true
src_paths = ["app"]

[tool.poetry]
name = "ai-osint-malware-analysis"
version = "0.1.0"
description = ""
authors = ["Gonzalo Gimeno <gonzalo.gimeno.torres@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
pandas = "2.2.2"
nltk = "3.8.1"
beautifulsoup4 = "4.12.3"
requests = "2.32.3"
pymongo = "4.8.0"


[tool.poetry.dev-dependencies]
isort = "==5.5.1"
black = "==22.3.0"
flake8 = "==3.9.2"
mypy = "==0.910"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"


[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

